// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BackgroundImageByUrlModuleCssNamespace {
  export interface IBackgroundImageByUrlModuleCss {
    backgroundImageByUrl: string;
  }
}

declare const BackgroundImageByUrlModuleCssModule: BackgroundImageByUrlModuleCssNamespace.IBackgroundImageByUrlModuleCss;

export = BackgroundImageByUrlModuleCssModule;
