// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace ChipListModuleCssNamespace {
  export interface IChipListModuleCss {
    chipList: string;
    chipListColumns: string;
    chipListInline: string;
    chipListItem: string;
  }
}

declare const ChipListModuleCssModule: ChipListModuleCssNamespace.IChipListModuleCss;

export = ChipListModuleCssModule;
