// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BookmarkModuleCssNamespace {
  export interface IBookmarkModuleCss {
    bookmark: string;
    bookmarkItem: string;
  }
}

declare const BookmarkModuleCssModule: BookmarkModuleCssNamespace.IBookmarkModuleCss;

export = BookmarkModuleCssModule;
