// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BackgroundPreviewModuleCssNamespace {
  export interface IBackgroundPreviewModuleCss {
    backgroundPreview: string;
  }
}

declare const BackgroundPreviewModuleCssModule: BackgroundPreviewModuleCssNamespace.IBackgroundPreviewModuleCss;

export = BackgroundPreviewModuleCssModule;
