// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BookmarkInlineListModuleCssNamespace {
  export interface IBookmarkInlineListModuleCss {
    bookmarkInlineList: string;
  }
}

declare const BookmarkInlineListModuleCssModule: BookmarkInlineListModuleCssNamespace.IBookmarkInlineListModuleCss;

export = BookmarkInlineListModuleCssModule;
