/* eslint-disable @typescript-eslint/no-var-requires */

const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const Dotenv = require('dotenv-webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { SourceMapDevToolPlugin } = require('webpack');
const package = require('./package.json');

if (process.env.NODE_ENV === undefined) {
  process.env.NODE_ENV = 'development';

  console.warn('Environment variable NODE_ENV is not defined, using "development" as default value');
}

if (process.env.BUILD_NUMBER === undefined) {
  process.env.BUILD_NUMBER = 0;

  console.warn('Environment variable BUILD_NUMBER is not defined, using "0" as default value');
}

if (process.env.TARGET_PLATFORM === undefined) {
  process.env.TARGET_PLATFORM = 'chromium';

  console.warn('Environment variable TARGET_PLATFORM is not defined, using "chromium" as default value');
}

const commonConfig = {
  context: path.join(__dirname, 'src'),
  devtool: false,
  entry: {
    newtab: './newtab/Newtab.tsx',
    options: './options/Options.tsx',
    background: './backgroundScript/background.ts',
  },
  mode: 'production',
  module: {
    rules: [
      {
        // include: path.join(__dirname, 'src', 'components'),
        test: /\.module\.css$/,
        use: [
          'style-loader',
          {
            loader: '@teamsupercell/typings-for-css-modules-loader',
            options: {
              disableLocalsExport: true,
              banner:
                '// Autogenerated with typings-for-css-modules-loader webpack loader. \n// Do not modify this file directly!',
            },
          },
          {
            loader: 'css-loader',
            options: {
              modules: {
                mode: 'local',
                auto: true,
                exportGlobals: true,
                localIdentName: '[local]--[hash:base64:5]',
                namedExport: false,
                exportLocalsConvention: 'camelCaseOnly',
                exportOnlyLocals: false,
              },
              importLoaders: 1,
            },
          },
          'postcss-loader',
        ],
      },
      {
        test: /\.svg(\?.*)?$/, // match img.svg and img.svg?param=value
        type: 'asset/inline',
        use: ['svg-transform-loader'],
      },
      {
        exclude: /node_modules/,
        loader: 'ts-loader',
        test: /\.tsx?$/,
      },
    ],
  },
  output: {
    filename: `[name]-${process.env.TARGET_PLATFORM}.js`,
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [
    new Dotenv({
      systemvars: true,
    }),
    new CopyWebpackPlugin({
      patterns: [
        {
          from: './manifest.json',
          transform(content) {
            const manifest = JSON.parse(content.toString());

            manifest.author = package.author.name;
            manifest.homepage_url = package.homepage;
            manifest.version = `${package.version}.${process.env.BUILD_NUMBER}`;
            manifest.version_name = `${package.version} build ${process.env.BUILD_NUMBER}`;
            manifest.background.service_worker = `/background-${process.env.TARGET_PLATFORM}.js`;

            switch (process.env.NODE_ENV) {
              case 'development':
                manifest.name = `${manifest.name} (dev)`;
                manifest.version_name = `${manifest.version_name} (dev)`;
                manifest.content_security_policy.extension_pages = `${manifest.content_security_policy.extension_pages};`;

                break;

              default:
                break;
            }

            return JSON.stringify(manifest, null, process.env.NODE_ENV === 'development' ? 2 : 0);
          },
        },
        { from: './logo.png' },
      ],
    }),
    new HtmlWebpackPlugin({
      chunks: ['newtab'],
      filename: 'newtab.html',
      inject: 'body',
      template: './newtab/newtab.ejs',
      templateParameters: {
        env: process.env.NODE_ENV,
      },
    }),
    new HtmlWebpackPlugin({
      chunks: ['options'],
      filename: 'options.html',
      inject: 'body',
      template: './options/options.ejs',
      templateParameters: {
        env: process.env.NODE_ENV,
      },
    }),
  ],
  resolve: {
    alias: {
      mdi: '@material-design-icons/svg',
    },
    extensions: ['.ts', '.tsx', '.js', 'jsx'],
  },
  target: 'web',
};

switch (process.env.NODE_ENV) {
  case 'production':
    commonConfig.plugins.push(
      new SourceMapDevToolPlugin({
        append: false,
        filename: '[file].map',
      }),
    );

    break;

  case 'development':
    commonConfig.devtool = 'inline-source-map';
    commonConfig.mode = 'development';

    commonConfig.watchOptions = {
      aggregateTimeout: 300,
      ignored: /node_modules/,
      poll: 1000,
    };

    break;

  default:
    throw Error('Unknown environment name');
}

module.exports = commonConfig;
