// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace OptionsModuleCssNamespace {
  export interface IOptionsModuleCss {
    options: string;
    optionsContent: string;
    optionsSidebar: string;
    optionsWrapper: string;
  }
}

declare const OptionsModuleCssModule: OptionsModuleCssNamespace.IOptionsModuleCss;

export = OptionsModuleCssModule;
