// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace FolderPopupModuleCssNamespace {
  export interface IFolderPopupModuleCss {
    bookmarkListContainer: string;
    folderPopup: string;
    folderPopupCloseButton: string;
    folderPopupContent: string;
    folderPopupHeader: string;
    folderPopupTitle: string;
    loading: string;
  }
}

declare const FolderPopupModuleCssModule: FolderPopupModuleCssNamespace.IFolderPopupModuleCss;

export = FolderPopupModuleCssModule;
