// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace ActionButtonModuleCssNamespace {
  export interface IActionButtonModuleCss {
    actionButton: string;
    actionButtonControl: string;
    actionButtonLoading: string;
    backgroundStripAnimation: string;
  }
}

declare const ActionButtonModuleCssModule: ActionButtonModuleCssNamespace.IActionButtonModuleCss;

export = ActionButtonModuleCssModule;
