// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace LabeledActionButtonModuleCssNamespace {
  export interface ILabeledActionButtonModuleCss {
    labeledActionButton: string;
  }
}

declare const LabeledActionButtonModuleCssModule: LabeledActionButtonModuleCssNamespace.ILabeledActionButtonModuleCss;

export = LabeledActionButtonModuleCssModule;
