// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BackgroundMediaFullScreenContainerModuleCssNamespace {
  export interface IBackgroundMediaFullScreenContainerModuleCss {
    backgroundMediaFullScreenContainer: string;
  }
}

declare const BackgroundMediaFullScreenContainerModuleCssModule: BackgroundMediaFullScreenContainerModuleCssNamespace.IBackgroundMediaFullScreenContainerModuleCss;

export = BackgroundMediaFullScreenContainerModuleCssModule;
