// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BackgroundMediaModuleCssNamespace {
  export interface IBackgroundMediaModuleCss {
    backgroundMedia: string;
    backgroundMediaLoading: string;
  }
}

declare const BackgroundMediaModuleCssModule: BackgroundMediaModuleCssNamespace.IBackgroundMediaModuleCss;

export = BackgroundMediaModuleCssModule;
