// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BookmarkSearchModuleCssNamespace {
  export interface IBookmarkSearchModuleCss {
    bookmarkSearch: string;
    bookmarkSearchCloseButton: string;
    bookmarkSearchField: string;
  }
}

declare const BookmarkSearchModuleCssModule: BookmarkSearchModuleCssNamespace.IBookmarkSearchModuleCss;

export = BookmarkSearchModuleCssModule;
