// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace PopupModuleCssNamespace {
  export interface IPopupModuleCss {
    bookmarkListContainer: string;
    loading: string;
    popup: string;
    popupCloseButton: string;
    popupContent: string;
    popupHeader: string;
    popupTitle: string;
  }
}

declare const PopupModuleCssModule: PopupModuleCssNamespace.IPopupModuleCss;

export = PopupModuleCssModule;
