// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace CheckboxModuleCssNamespace {
  export interface ICheckboxModuleCss {
    backgroundStripAnimation: string;
    checkbox: string;
    checkboxControl: string;
    checkboxControlIndeterminate: string;
    checkboxLoading: string;
  }
}

declare const CheckboxModuleCssModule: CheckboxModuleCssNamespace.ICheckboxModuleCss;

export = CheckboxModuleCssModule;
