// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace LabeledCheckboxModuleCssNamespace {
  export interface ILabeledCheckboxModuleCss {
    labeledCheckbox: string;
  }
}

declare const LabeledCheckboxModuleCssModule: LabeledCheckboxModuleCssNamespace.ILabeledCheckboxModuleCss;

export = LabeledCheckboxModuleCssModule;
