// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BookmarkWorkspaceModuleCssNamespace {
  export interface IBookmarkWorkspaceModuleCss {
    bookmarkWorkspace: string;
    bookmarkWorkspaceLoading: string;
  }
}

declare const BookmarkWorkspaceModuleCssModule: BookmarkWorkspaceModuleCssNamespace.IBookmarkWorkspaceModuleCss;

export = BookmarkWorkspaceModuleCssModule;
