// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace NewtabModuleCssNamespace {
  export interface INewtabModuleCss {
    newtabWrapper: string;
  }
}

declare const NewtabModuleCssModule: NewtabModuleCssNamespace.INewtabModuleCss;

export = NewtabModuleCssModule;
