// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace OptionsSearchFormModuleCssNamespace {
  export interface IOptionsSearchFormModuleCss {
    optionsSearchFormCategoryList: string;
  }
}

declare const OptionsSearchFormModuleCssModule: OptionsSearchFormModuleCssNamespace.IOptionsSearchFormModuleCss;

export = OptionsSearchFormModuleCssModule;
