// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace OptionsCategoryModuleCssNamespace {
  export interface IOptionsCategoryModuleCss {
    optionsCategory: string;
    optionsCategoryButton: string;
    optionsCategoryIcon: string;
    optionsCategoryLabel: string;
  }
}

declare const OptionsCategoryModuleCssModule: OptionsCategoryModuleCssNamespace.IOptionsCategoryModuleCss;

export = OptionsCategoryModuleCssModule;
