// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BottomToolbarModuleCssNamespace {
  export interface IBottomToolbarModuleCss {
    bottomToolbar: string;
    bottomToolbarItems: string;
  }
}

declare const BottomToolbarModuleCssModule: BottomToolbarModuleCssNamespace.IBottomToolbarModuleCss;

export = BottomToolbarModuleCssModule;
