// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace LabeledTextFieldModuleCssNamespace {
  export interface ILabeledTextFieldModuleCss {
    labeledTextField: string;
    labeledTextFieldLabel: string;
    labeledTextFieldLabelAndControlWrapper: string;
  }
}

declare const LabeledTextFieldModuleCssModule: LabeledTextFieldModuleCssNamespace.ILabeledTextFieldModuleCss;

export = LabeledTextFieldModuleCssModule;
