// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace TextFieldModuleCssNamespace {
  export interface ITextFieldModuleCss {
    backgroundStripAnimation: string;
    textField: string;
    textFieldControl: string;
    textFieldLoading: string;
  }
}

declare const TextFieldModuleCssModule: TextFieldModuleCssNamespace.ITextFieldModuleCss;

export = TextFieldModuleCssModule;
