// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BookmarkCategoryModuleCssNamespace {
  export interface IBookmarkCategoryModuleCss {
    bookmarkCategory: string;
    bookmarkCategoryTitle: string;
  }
}

declare const BookmarkCategoryModuleCssModule: BookmarkCategoryModuleCssNamespace.IBookmarkCategoryModuleCss;

export = BookmarkCategoryModuleCssModule;
