// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace DropdownSelectModuleCssNamespace {
  export interface IDropdownSelectModuleCss {
    backgroundStripAnimation: string;
    dropdownSelect: string;
    dropdownSelectControl: string;
    dropdownSelectLoading: string;
  }
}

declare const DropdownSelectModuleCssModule: DropdownSelectModuleCssNamespace.IDropdownSelectModuleCss;

export = DropdownSelectModuleCssModule;
