// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace LabeledDropdownSelectModuleCssNamespace {
  export interface ILabeledDropdownSelectModuleCss {
    labeledDropdownSelect: string;
    labeledDropdownSelectControl: string;
    labeledDropdownSelectLabel: string;
    labeledDropdownSelectLabelAndControlWrapper: string;
  }
}

declare const LabeledDropdownSelectModuleCssModule: LabeledDropdownSelectModuleCssNamespace.ILabeledDropdownSelectModuleCss;

export = LabeledDropdownSelectModuleCssModule;
