// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace ChipModuleCssNamespace {
  export interface IChipModuleCss {
    backgroundStripAnimation: string;
    chip: string;
    chipBody: string;
    chipBodyLoading: string;
    chipBodyRounded: string;
    chipBodySquared: string;
    chipIcon: string;
    chipLabel: string;
  }
}

declare const ChipModuleCssModule: ChipModuleCssNamespace.IChipModuleCss;

export = ChipModuleCssModule;
