// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace ChipModuleCssNamespace {
  export interface IChipModuleCss {
    backgroundStripAnimation: string;
    chip: string;
    chipIcon: string;
    chipIconInline: string;
    chipLabel: string;
    chipRounded: string;
    chipSquared: string;
    loading: string;
  }
}

declare const ChipModuleCssModule: ChipModuleCssNamespace.IChipModuleCss;

export = ChipModuleCssModule;
