// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace AboutAppModuleCssNamespace {
  export interface IAboutAppModuleCss {
    aboutApp: string;
    aboutAppName: string;
  }
}

declare const AboutAppModuleCssModule: AboutAppModuleCssNamespace.IAboutAppModuleCss;

export = AboutAppModuleCssModule;
