// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BookmarkListModuleCssNamespace {
  export interface IBookmarkListModuleCss {
    bookmarkList: string;
    bookmarkListItem: string;
  }
}

declare const BookmarkListModuleCssModule: BookmarkListModuleCssNamespace.IBookmarkListModuleCss;

export = BookmarkListModuleCssModule;
