// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace BookmarkBrowserModuleCssNamespace {
  export interface IBookmarkBrowserModuleCss {
    noBookmarksMessage: string;
  }
}

declare const BookmarkBrowserModuleCssModule: BookmarkBrowserModuleCssNamespace.IBookmarkBrowserModuleCss;

export = BookmarkBrowserModuleCssModule;
