// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace ParagraphModuleCssNamespace {
  export interface IParagraphModuleCss {
    paragraph: string;
  }
}

declare const ParagraphModuleCssModule: ParagraphModuleCssNamespace.IParagraphModuleCss;

export = ParagraphModuleCssModule;
