// Autogenerated with typings-for-css-modules-loader webpack loader.
// Do not modify this file directly!
declare namespace PopupManagerModuleCssNamespace {
  export interface IPopupManagerModuleCss {
    popupManager: string;
  }
}

declare const PopupManagerModuleCssModule: PopupManagerModuleCssNamespace.IPopupManagerModuleCss;

export = PopupManagerModuleCssModule;
